name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      PASSWORD:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      
    - name: Dump Password
      run: |
        bash ./test.sh
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
